/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import controllers.PdfGeneratorController;
import controllers.UserManagemetController;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joanp
 */
public class GenerateByDelays extends javax.swing.JFrame {

    private final PdfGeneratorController controller;
    private final UserManagemetController userManagemetController;

    /**
     * Creates new form GenerateByDelays
     */
    public GenerateByDelays() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar Reporte");
        setResizable(false);
        controller = new PdfGeneratorController();
        userManagemetController = new UserManagemetController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        cbxTypesReport = new javax.swing.JComboBox<>();
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/fondo-blanco.jpg"));
        Image image = icon.getImage();
        mainDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        cbxTypesReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de reporte", "General", "Fecha", "Usuario" }));
        cbxTypesReport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTypesReportItemStateChanged(evt);
            }
        });

        mainDesktop.setBorder(null);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(cbxTypesReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDesktop)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cbxTypesReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktop))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTypesReportItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTypesReportItemStateChanged
        //prueba luego creo ventanas, (deben ser internal)
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            switch (cbxTypesReport.getSelectedIndex()) {
                case 1:

                    Test test = new Test();
                    mainDesktop.add(test);
                    test.setVisible(true);
                    break;
//                GenerateGeneralReportView view = new GenerateGeneralReportView(this);
//                mainDesktop.add(view);
//                view.setVisible(true);
                case 2:
//                GenerateByDatesReportView view2 = new GenerateByDatesReportView(this);
//                mainDesktop.add(view2);
//                view2.setVisible(true);
                    break;
                case 3:
//                new GenerateByUserReportView(admin, this).setVisible(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Selecciona un tipo de reporte");
                    break;
            }
        }

    }//GEN-LAST:event_cbxTypesReportItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> cbxTypesReport;
    private javax.swing.JDesktopPane mainDesktop;
    // End of variables declaration//GEN-END:variables
}
